### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by fergmac** [bcgov/nr-nmp#40]
**Describe the task**
When we deploy to Dev, Test, Prod we need to apply database migrations based off of our local work. We can handle this in GitHub actions. We need to decide if we are using a database migration tool or custom script.

**Acceptance Criteria**
- [x] database deploys to Dev, Test, Prod
- [x] database tool includes database updates in migration file
- [x] migration file is applied to database as part of GitHub action workflows

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by dallascrichmond** [comment]
- Did some research and chose Prisma over typeORM for it's simplicity and maintainability over time as new dev get brought on.
- Did other research and created a confluence doc explaining the technology choice as well as outlining a few key points for each.
- All technologies were chosen with the idea of maintainability in mind
- Link to Confluence: https://apps.nrs.gov.bc.ca/int/confluence/display/SUSTEAM/NR-NMP+Tech+Stack+Planning
