### ISSUE TITLE
Push NR-NMP to Dev

### ISSUE THREAD

**Issue by Keegnan** [bcgov/nr-nmp#8]
**Describe the task**
The new OpenShift has been approved and the code need to be pushed to Dev environment.

**Acceptance Criteria**
- [ ] project pushes to dev

**Additional context**
- Use the QuickStart template 
- connect with Sustainment Lead Dev for any issues/troubleshooting

**Comment by dallascrichmond** [comment]
Updated acceptance criteria. Misunderstood the order of operations when originally creating this ticket. Need to go to dev first and then test and prod.
